global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'laravel_app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: /metrics

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']
